#!/usr/bin/env bash

# Exit the script if any statement returns a non-true return value
set -e
# Show error if used undefined variable
set -u
# Pipe fail if any one of the pipe command failed
set -o pipefail

_sed=$([ "$(uname)" = "Darwin" ] && echo "sed -E" || echo "sed -r");

SVN_REPO_URL=$(svn info | grep "Repository Root:" | awk '{ print $3; }')
SVN_REPO_DIR=$(svn info | grep "Working Copy Root Path:" | awk '{ print $5; }')
REPO_SUB_DIR=$(svn info | grep "Relative URL:" \
    | awk 'sub(/\^\//,"",$3) sub(/\^\\/,"",$3) { print $3; }')

######################################################################
# Version file to auto sync SVN repo info
VS_VFILE="${SVN_REPO_DIR}/version"

if true; then # Example 1
VS_SVN_SUB_RV="MY_SVN_SUB_REVERSION"   # Can not ignore, must be 0 ~ 9
VS_SVN_REPO_RV="MY_SVN_REPO_REVERSION" # Can not ignore, must be 0 ~ 9
VS_SVN_REPO_URL="MY_SVN_REPO_URL"      # string like "svn://localhost/abc" or "http://localhost/abc"
VS_MODIFY_TIME="MY_SVN_MODIFY_TIME"    # string like "2019-01-19 01:00:52 +0800"
fi

if false; then # Example 2
VS_SVN_SUB_RV="const int MY_SVN_SUB_REVERSION ="
VS_SVN_REPO_RV="const int MY_SVN_REPO_REVERSION ="
VS_SVN_REPO_URL="const char *MY_SVN_REPO_URL ="
VS_MODIFY_TIME="const char * MY_SVN_MODIFY_TIME ="
fi

if false; then # Example 3
VS_SVN_SUB_RV="const char MY_SVN_SUB_REVERSION ="
VS_SVN_REPO_RV="const char MY_SVN_REPO_REVERSION ="
VS_SVN_REPO_URL="const String MY_SVN_REPO_URL ="
VS_MODIFY_TIME="const String MY_SVN_MODIFY_TIME ="
fi

if false; then # Example 4
 VS_SVN_SUB_RV="const String MY_SVN_SUB_REVERSION  ="
VS_SVN_REPO_RV="const String MY_SVN_REPO_REVERSION ="
VS_MODIFY_TIME="const String MY_SVN_MODIFY_TIME    ="
fi

if false; then # Example 5
 VS_SVN_SUB_RV=" const String MY_SVN_SUB_REVERSION  = "
VS_SVN_REPO_RV="const  String MY_SVN_REPO_REVERSION = "
VS_MODIFY_TIME="const  String  MY_SVN_MODIFY_TIME   = "
fi
######################################################################
SVN_REPO_RV=$(svn info | grep "Revision:" | awk '{ print $2; }')
SVN_SUB_RV=$(svn info | grep "Last Changed Rev:" | awk '{ print $4; }')
SVN_MODIFY_TIME=$(svn info | grep "Last Changed Date:" \
    | awk '{ print $4, $5, $6; }')

[ -z "${REPO_SUB_DIR}" ] && REPO_SUB_DIR="$PWD"

echo "SVN Sub Reversion   : ${SVN_SUB_RV}"
echo "SVN Repo Reversion  : ${SVN_REPO_RV}"
echo "SVN Modify Date Time: ${SVN_MODIFY_TIME}"
echo "SVN Repo Remote URL : ${SVN_REPO_URL}"
echo "SVN Local Root Path : ${SVN_REPO_DIR}"
echo "SVN Working Path    : ${REPO_SUB_DIR}"

# Escape meta-char for RegExp
#   (   =>  \(
# space =>  \s+
_VS_SVN_REPO_URL_=$(echo "${VS_SVN_REPO_URL}" \
    | awk -F';' 'sub(/\(/,"\(",$1) gsub(/ /,"\s+",$1) gsub(/\*/,"\*",$1) { print $1; }');
_VS_SVN_SUB_RV_=$(echo "${VS_SVN_SUB_RV}" \
    | awk -F';' 'sub(/\(/,"\(",$1) gsub(/ /,"\s+",$1) gsub(/\*/,"\*",$1) { print $1; }');
_VS_SVN_REPO_RV_=$(echo "${VS_SVN_REPO_RV}" \
    | awk -F';' 'sub(/\(/,"\(",$1) gsub(/ /,"\s+",$1) gsub(/\*/,"\*",$1) { print $1; }');
_VS_MODIFY_TIME_=$(echo "${VS_MODIFY_TIME}" \
    | awk -F';' 'sub(/\(/,"\(",$1) gsub(/ /,"\s+",$1) gsub(/\*/,"\*",$1) { print $1; }');

# 2019-01-19 01:00:52 +0800
REGEXP_TMZ="[0-9]{4}"
REGEXP_YMD="[0-9]{4}-[0-9]{2}-[0-9]{2}"
REGEXP_HMS="[0-9]{2}:[0-9]{2}:[0-9]{2}"
REGEXP_DTZ="${REGEXP_YMD}\s+${REGEXP_HMS}\s+\+${REGEXP_TMZ}"

# RegExp Pattern
REGEXP_SVN_SUB_RV="^(${_VS_SVN_SUB_RV_}\s+\\\"*'*)([0-9A-Za-z]+)('*\\\"*\s*.*)$";
REGEXP_SVN_REPO_RV="^(${_VS_SVN_REPO_RV_}\s+\\\"*'*)([0-9A-Za-z]+)('*\\\"*\s*.*)$";
REGEXP_SVN_REPO_URL="^(${_VS_SVN_REPO_URL_}\s+\\\"*)(((http(s?)|svn):\/\/)[0-9A-Za-z_\\\\\/\.-]+[^\\\"])(\\\"*\s*.*)$";
REGEXP_MODIFY_TIME="^(${_VS_MODIFY_TIME_}\s+\\\"*)(${REGEXP_DTZ})(\\\"*\s*.*)$";

${_sed} -i.bk "s/${REGEXP_SVN_SUB_RV}/\1${SVN_SUB_RV}\3/" ${VS_VFILE};
${_sed} -i.bk "s/${REGEXP_SVN_REPO_RV}/\1${SVN_REPO_RV}\3/" ${VS_VFILE};
${_sed} -i.bk "s/${REGEXP_MODIFY_TIME}/\1${SVN_MODIFY_TIME}\3/" ${VS_VFILE};

_SVN_REPO_URL_=$(echo "${SVN_REPO_URL}" \
    | awk 'gsub(/\\/,"\\\\\\",$1) gsub(/\//,"\/",$1) gsub(/\./,"\.",$1) \
           gsub(/\-/,"\-",$1) gsub(/\:/,"\:",$1) { print $1; }');
${_sed} -i.bk "s/${REGEXP_SVN_REPO_URL}/\1${_SVN_REPO_URL_}\6/" ${VS_VFILE};

rm -rf ${VS_VFILE}.bk
