#!/usr/bin/env bash

REPO_HOOKS_VERSION="v0.1.1";
# https://github.com/gkide/repo-hooks

# Exit the script if any statement returns a non-true return value
set -e
# Show error if used undefined variable
set -u
# Pipe fail if any one of the pipe command failed
set -o pipefail

# Software Release Life Cycle & Candidates
#
# - Semantic Version
#   https://semver.org/
# - Software Release Life Cycle
#   https://en.wikipedia.org/wiki/Software_release_life_cycle
# - Also see
#   1. https://nodejs.org/en/about/releases/
#   2. https://github.com/nodejs/Release#readme
#######################################################################
# dev/pre/nightly => alpha => beta => rc => lts/stable/release => eol #
#######################################################################
#
# - dev/pre/nightly
#   Refers to all activities performed before formal testing, like:
#   requirements analysis, software design, and related inter-testing
#   Code from the default branch built every 24-hours when there are changes.
#   Those type of build should be used with caution!
#
# - alpha
#   The first phase to begin software testing, normally using of
#   white-box, black-box or gray-box testing techniques, and may
#   not contain all of the features that the final version has.
#   It usually ends with features freeze, indicating that no more
#   features will be added to the software, known as feature complete.
#
# - beta
#   The second phase just following alpha, generally begins when the
#   software is feature complete but likely to contain a number of known
#   or unknown bugs, may have speed or performance issues, crashes or data
#   loss. The beta stage is focus on usability, for reducing impacts to the
#   end-users. The beta version is normally formally first release to user.
#
# - rc
#   The release candidate (RC), is the third phase of software development,
#   with potential to be the final version, which is ready to release unless
#   significant bugs emerge. In this stage, features are complete and stable,
#   tested through one or more beta cycles, no entirely new features will be
#   added. There can still have bug fix, change the documentation and testings.
#
# - lts/stable/release
#   The final normal release version
#
# - eol
#   No longer supported, the release reached the end-of-life.
SRLC_REG="([a-z]+)*(\.*([0-9]+))*(\+*([0-9a-f]+))*";
SRLC_CAN="dev pre nightly alpha beta rc stable release lts eol";

# Current directory of full path with symbolic link resolved
THIS_DIR="$(realpath ${0%/*})";

# Import normal shell function-util
# - IS_DEBUG_MODE=true;
# - IS_VERBOSE_MODE=true;
source ${THIS_DIR}/utils.sh;
IS_DEBUG_MODE=false;
__SKIP_ALL_MSG=false;

SRLC_HELP="";
for item in ${SRLC_CAN}; do
    [ -n "${SRLC_HELP}" ] && SRLC_HELP="${SRLC_HELP}, ";
    SRLC_HELP="${SRLC_HELP}$(valMsg ${item})";
done

# The TWEAK help & example usage
SRLC_HELP="${SRLC_HELP}

The $(keyMsg TWEAK) format as following, like:

    X
    X.123..
    X+ab01...
    X.123..+ab01...
";

_sed=$([ "$(uname)" = "Darwin" ] && echo "sed -E" || echo "sed -r");

# Interactive mode or not
IS_INTERACTIVE=true;
# Run testing
IS_TESTING=false;

# Semantic version config if not set then use the default
USR_CONFIG="";

for item in $*; do
    if [ "0" = "$#" ]; then
        break;
    fi

    KEY=$(echo ${item} | sed "s/\([a-zA-Z]*\)=\([a-zA-Z0-9\/\._-]*\)/\1/g");
    VAL=$(echo ${item} | sed "s/\([a-zA-Z]*\)=\([a-zA-Z0-9\/\._-]*\)/\2/g");
    # infoMsg "$# [$item] => [$KEY], [$VAL]";

    [ "$KEY" = "" -o "$KEY" = "${item}" ] && break;
    [ "$VAL" = "" -o "$VAL" = "${item}" ] && break;

    if [ "CONFIG" = "$KEY" ]; then
        USR_CONFIG="$VAL";
        continue;
    fi

    if [ "INTERACTIVE" = "$KEY" ]; then
        IS_INTERACTIVE=$VAL;
        continue;
    fi

    if [ "TESTING" = "$KEY" ]; then
        __SKIP_ALL_MSG=true;
        IS_TESTING=true;
        continue;
    fi
done

# If true, utils functions keep quiet
SKIP_ALL_MSG=$__SKIP_ALL_MSG;

# Semantic version config not set, use the default of current working directory
if [ "${USR_CONFIG}" = "" ]; then
    USR_CONFIG=.sync-release.sh
fi

if [ ! -f "${USR_CONFIG}" ]; then
    infoMsg "Usage: ${0##*/} [CONFIG=config] [TESTING=true]";
    errMsg "Release config do not exits $(keyMsg ${PWD}/${USR_CONFIG})";
fi

# User configuration
# - REPO_DIR
# - REPO_VCS
# - VS_VFILE
source ${USR_CONFIG};
USR_CONFIG=$(realpath -s ${USR_CONFIG}); # don't expand symlinks

# Change to user repo directory
if [ ! -d ${REPO_DIR} ]; then
    errMsg "Do not exits repo $(keyMsg ${REPO_DIR})";
fi
cd ${REPO_DIR}
REPO_DIR=$(realpath -s ${REPO_DIR}); # don't expand symlinks

# Checking is GIT or SVN
VCS="$(getSupportedVCS $REPO_VCS)";
[ "${VCS}" = "SVN" -a ! -d ${PWD}/.svn ] \
    && errMsg "Repo is not $(keyMsg SVN)";
[ "${VCS}" = "GIT" -a ! -d ${PWD}/.git ] \
    && errMsg "Repo is not $(keyMsg GIT)";

isGitRepo=false;
isSvnRepo=false;
case "${VCS}" in
    "GIT")
        isGitRepo=true;
        ;;
    "SVN")
        isSvnRepo=true;
        ;;
esac

# Semantic version file to sync
if [ ! -f ${VS_VFILE} ]; then
    errMsg "Do not exits repo info file $(keyMsg ${VS_VFILE})";
fi

VS_VFILE=$(pathFixForWindows "${VS_VFILE}")
REPO_DIR=$(pathFixForWindows "${REPO_DIR}")
USR_CONFIG=$(pathFixForWindows "${USR_CONFIG}")

# The version & config file should be one file of the repo subdirectory
fullPath=$(realpath -s ${VS_VFILE}); # don't expand symlinks
isRepoFile=${fullPath#${REPO_DIR}/}; # remove '${REPO_DIR}/'
if [ "${isRepoFile}" = "${fullPath}" ]; then
    errMsg "$(keyMsg ${VCS}): $(valMsg ${fullPath}) NOT in the repo
       $(keyMsg ${REPO_DIR})";
fi
VS_VFILE=${REPO_DIR}/${isRepoFile};

fullPath=$(realpath -s ${USR_CONFIG}); # don't expand symlinks
isRepoFile=${fullPath#${REPO_DIR}/}; # remove '${REPO_DIR}/'
if [ "${isRepoFile}" = "${fullPath}" ]; then
    errMsg "$(keyMsg ${VCS}): $(valMsg ${fullPath}) NOT in the repo
       $(keyMsg ${REPO_DIR})";
fi
USR_CONFIG=${REPO_DIR}/${isRepoFile};

REPO_NAME=$(basename ${REPO_DIR});
infoMsg "----------------------------------------------------------------";
infoMsg "Just Enter with nothing will use the default [value]";
infoMsg "----------------------------------------------------------------";
infoMsg "$(keyMsg ${VCS}): Repo: $(valMsg ${REPO_DIR})";
infoMsg "$(keyMsg ${VCS}): Config: $(keyMsg ${REPO_NAME})/$(valMsg ${USR_CONFIG#${REPO_DIR}/})";
infoMsg "$(keyMsg ${VCS}): SyncInfo: $(keyMsg ${REPO_NAME})/$(valMsg ${VS_VFILE#${REPO_DIR}/})";

function escapeRegExpMetaChar()
{
    STR="$1";

    # *         \*
    STR=$(escREMC '*' "$STR");

    # space     \s+
    STR=$(escREMC ' ' "$STR");
    STR=$(escREMC '\t' "$STR");

    # (         \(
    # )         \)
    STR=$(escREMC '(' "$STR");
    STR=$(escREMC ')' "$STR");

    # [         \[
    # ]         \]
    STR=$(escREMC '[' "$STR");
    STR=$(escREMC ']' "$STR");

    printf "${STR}";
    return 0;
}

isDefined="$(echo ${VS_MAJOR-NotDefine})"
if [ "${isDefined}" = "NotDefine" ]; then
    _VS_MAJOR_="DO_NOT_USED_MAJOR";
else
    _VS_MAJOR_=$(escapeRegExpMetaChar "${VS_MAJOR}");
    VS_MAJOR=$(escREMC '*' "${VS_MAJOR}");
    VS_MAJOR=$(escREMC '[' "${VS_MAJOR}");
    VS_MAJOR=$(escREMC ']' "${VS_MAJOR}");
    #debugMsg "$(keyMsg Key Major): [$(valMsg ${VS_MAJOR})]";
fi

isDefined="$(echo ${VS_MINOR-NotDefine})"
if [ "${isDefined}" = "NotDefine" ]; then
    _VS_MINOR_="DO_NOT_USED_MINOR";
else
    _VS_MINOR_=$(escapeRegExpMetaChar "${VS_MINOR}");
    VS_MINOR=$(escREMC '*' "${VS_MINOR}");
    VS_MINOR=$(escREMC '[' "${VS_MINOR}");
    VS_MINOR=$(escREMC ']' "${VS_MINOR}");
    #debugMsg "$(keyMsg Key Minor): [$(valMsg ${VS_MINOR})]";
fi

isDefined="$(echo ${VS_PATCH-NotDefine})"
if [ "${isDefined}" = "NotDefine" ]; then
    _VS_PATCH_="DO_NOT_USED_PATCH";
else
    _VS_PATCH_=$(escapeRegExpMetaChar "${VS_PATCH}");
    VS_PATCH=$(escREMC '*' "${VS_PATCH}");
    VS_PATCH=$(escREMC '[' "${VS_PATCH}");
    VS_PATCH=$(escREMC ']' "${VS_PATCH}");
    #debugMsg "$(keyMsg Key Patch): [$(valMsg ${VS_PATCH})]";
fi

isDefined="$(echo ${VS_TWEAK-NotDefine})"
if [ "${isDefined}" = "NotDefine" ]; then
    _VS_TWEAK_="DO_NOT_USED_TWEAK";
else
    _VS_TWEAK_=$(escapeRegExpMetaChar "${VS_TWEAK}");
    VS_TWEAK=$(escREMC '*' "${VS_TWEAK}");
    VS_TWEAK=$(escREMC '[' "${VS_TWEAK}");
    VS_TWEAK=$(escREMC ']' "${VS_TWEAK}");
    #debugMsg "$(keyMsg Key Tweak): [$(valMsg ${VS_TWEAK})]";
fi

isDefined="$(echo ${VS_SEMVER-NotDefine})"
if [ "${isDefined}" = "NotDefine" ]; then
    _VS_SEMVER_="DO_NOT_USED_SEMVER";
else
    _VS_SEMVER_=$(escapeRegExpMetaChar "${VS_SEMVER}");

    VS_SEMVER=$(escREMC '*' "${VS_SEMVER}");
    VS_SEMVER=$(escREMC '[' "${VS_SEMVER}");
    VS_SEMVER=$(escREMC ']' "${VS_SEMVER}");
    VS_SEMVER=$(escREMC ' ' "$VS_SEMVER");
    VS_SEMVER=$(escREMC '\t' "$VS_SEMVER");
fi

# Version RegExp Pattern
REGEXP_MAJOR="^(${_VS_MAJOR_}\s*\\\"*'*)([0-9]+)('*\\\"*\s*.*)$";
REGEXP_MINOR="^(${_VS_MINOR_}\s*\\\"*'*)([0-9]+)('*\\\"*\s*.*)$";
REGEXP_PATCH="^(${_VS_PATCH_}\s*\\\"*'*)([0-9]+)('*\\\"*\s*.*)$";
REGEXP_TWEAK="^(${_VS_TWEAK_}\s*\\\"*'*)([a-z0-9\.\+]+)*('*\\\"*\s*.*)$";
REGEXP_SEMVER="^(${_VS_SEMVER_}\s*\\\"*'*)([a-z0-9\.\+-]+)('*\\\"*\s*.*)$";

#debugMsg "$(keyMsg RegExp Major): [$(valMsg ${REGEXP_MAJOR})]";
#debugMsg "$(keyMsg RegExp Minor): [$(valMsg ${REGEXP_MINOR})]";
#debugMsg "$(keyMsg RegExp Patch): [$(valMsg ${REGEXP_PATCH})]";
#debugMsg "$(keyMsg RegExp Tweak): [$(valMsg ${REGEXP_TWEAK})]";
#debugMsg "$(keyMsg RegExp SemVer): [$(valMsg ${REGEXP_SEMVER})]";

# Semver From The Source Code
if [ "$_VS_SEMVER_" != "DO_NOT_USED_SEMVER" ]; then
    VERSION_SEMVER=$(grep "${VS_SEMVER}" ${VS_VFILE} \
        | ${_sed} "s/${REGEXP_SEMVER}/\2/");
    #debugMsg "$(keyMsg SemVer): [$(valMsg ${VERSION_SEMVER})]";

    VERSION_MAJOR=$(echo "${VERSION_SEMVER}" \
        | ${_sed} "s/([A-Za-z]*)([0-9]+)\.([0-9]+)\.([0-9]+)([-+]([a-z0-9\.\+]+))*/\2/");
    VERSION_MINOR=$(echo "${VERSION_SEMVER}" \
        | ${_sed} "s/([A-Za-z]*)([0-9]+)\.([0-9]+)\.([0-9]+)([-+]([a-z0-9\.\+]+))*/\3/");
    VERSION_PATCH=$(echo "${VERSION_SEMVER}" \
        | ${_sed} "s/([A-Za-z]*)([0-9]+)\.([0-9]+)\.([0-9]+)([-+]([a-z0-9\.\+]+))*/\4/");
    VERSION_TWEAK=$(echo "${VERSION_SEMVER}" \
        | ${_sed} "s/([A-Za-z]*)([0-9]+)\.([0-9]+)\.([0-9]+)([-+]([a-z0-9\.\+]+))*/\6/");
else
    VERSION_MAJOR=$(grep "${VS_MAJOR}" ${VS_VFILE} \
        | ${_sed} "s/${REGEXP_MAJOR}/\2/");
    VERSION_MINOR=$(grep "${VS_MINOR}" ${VS_VFILE} \
        | ${_sed} "s/${REGEXP_MINOR}/\2/");
    VERSION_PATCH=$(grep "${VS_PATCH}" ${VS_VFILE} \
        | ${_sed} "s/${REGEXP_PATCH}/\2/");
    VERSION_TWEAK=$(grep "${VS_TWEAK}" ${VS_VFILE} \
        | ${_sed} "s/${REGEXP_TWEAK}/\2/");
fi

if [ -z "${VERSION_MAJOR}" -o -z "{$VERSION_MINOR}" -o -z "${VERSION_PATCH}" ]; then
    errMsg "Get semantic version from $(keyMsg ${VS_VFILE}) failed";
fi

# Save the previous version
PREV_MAJOR=${VERSION_MAJOR}
PREV_MINOR=${VERSION_MINOR}
PREV_PATCH=${VERSION_PATCH}
PREV_TWEAK_NC=${VERSION_TWEAK}

_major_="$(valMsg ${VERSION_MAJOR})";
_minor_="$(valMsg ${VERSION_MINOR})";
_patch_="$(valMsg ${VERSION_PATCH})";
_tweak_="$(valMsg ${VERSION_TWEAK})";

# Check release branch for GIT repo
if ${isGitRepo}; then
    CURRENT_BRANCH=$(git status | head -n 1 | awk '{print $3}');
    infoMsg "----------------------------------------------------------------";
    infoMsgL "Release Branch $(valMsg ${CURRENT_BRANCH}) (y/n) [y]: ";
    usrInput="Y"; # default value for none interactive mode
    ${IS_TESTING} && usrInput="Y"; # testing & none interactive mode
    ${IS_INTERACTIVE} && read -p "" usrInput;
    ! ${IS_INTERACTIVE} && ! ${__SKIP_ALL_MSG} echo "";

    [ -z "${usrInput}" ] && usrInput='Y'; # Just Enter is Yes

    if ! isYes "${usrInput}"; then
        errMsg "Release Stop.";
    fi
fi

s_major="${_major_}"
s_minor="${_minor_}"
s_patch="${_patch_}"
s_tweak="${_tweak_}"

PREV_TWEAK="";
PREV_TWEAK_TXT="";
PREV_TWEAK_NUM="";
PREV_TWEAK_SHA="";
[ -n "${VERSION_TWEAK}" ] && {
    PREV_TWEAK_TXT=$(echo "${VERSION_TWEAK}" | ${_sed} "s/^${SRLC_REG}$/\1/");
    PREV_TWEAK_NUM=$(echo "${VERSION_TWEAK}" | ${_sed} "s/^${SRLC_REG}$/\3/");
    PREV_TWEAK_SHA=$(echo "${VERSION_TWEAK}" | ${_sed} "s/^${SRLC_REG}$/\5/");

    PREV_TWEAK_TXT=$(echo "${PREV_TWEAK_TXT}" | ${_sed} -n "/^[a-z]*$/p");
    PREV_TWEAK_NUM=$(echo "${PREV_TWEAK_NUM}" | ${_sed} -n "/^[0-9]*$/p");
    PREV_TWEAK_SHA=$(echo "${PREV_TWEAK_SHA}" | ${_sed} -n "/^[a-f0-9]*$/p");

    if [ -z "${PREV_TWEAK_TXT}" -a -z "${PREV_TWEAK_NUM}" -a -z "${PREV_TWEAK_SHA}" ]; then
        # get relative path to REPO
        repo_fname=${VS_VFILE#*${REPO_DIR}/}
        errMsg "$(keyMsg ${repo_fname}) TWEAK shoule be one of:\n
    ${SRLC_HELP}";
    fi

    PREV_TWEAK="$(valMsg ${PREV_TWEAK_TXT})";
    if [ -n "${PREV_TWEAK_NUM}" ]; then
        if [ -n "${PREV_TWEAK}" ]; then
            PREV_TWEAK="${PREV_TWEAK}.$(valMsg ${PREV_TWEAK_NUM})";
        else
            PREV_TWEAK="$(valMsg ${PREV_TWEAK_NUM})";
        fi
    fi

    if [ -n "${PREV_TWEAK_SHA}" ]; then
        if [ -n "${PREV_TWEAK}" ]; then
            PREV_TWEAK="${PREV_TWEAK}+$(valMsg ${PREV_TWEAK_SHA})";
        else
            PREV_TWEAK="$(valMsg ${PREV_TWEAK_SHA})";
        fi
    fi

    #debugMsg "$(keyMsg Tweak old text): [$(valMsg ${PREV_TWEAK_TXT})]";
    #debugMsg "$(keyMsg Tweak old nums): [$(valMsg ${PREV_TWEAK_NUM})]";
    #debugMsg "$(keyMsg Tweak old hash): [$(valMsg ${PREV_TWEAK_SHA})]";
}

# Update CHANGELOG.md & get next auto semver
# SEMVER_TAG is like '1.2.3' or '1.2.3-1'
CHANGELOG="CHANGELOG.md";
CHANGELOG_UPDATE=false;
infoMsgL "Changelog Update ($(keyMsg SKIP)) [$(valMsg ${CHANGELOG})]: ";
usrInput="CHANGELOG.md"; # default value for none interactive mode
${IS_TESTING} && usrInput="CHANGELOG.md"; # testing & none interactive mode
${IS_INTERACTIVE} && read -p "" usrInput;
! ${IS_INTERACTIVE} && ! ${__SKIP_ALL_MSG} echo "";

# Skip changelog update
if [ "${usrInput}" != "SKIP" ]; then
    CHANGELOG_UPDATE=true;
    [ -n "${usrInput}" ] && CHANGELOG="${usrInput}";

    if [ ! -f ${CHANGELOG} ]; then
        touch ${CHANGELOG}
    fi

    fullPath=$(realpath -m ${CHANGELOG});
    isRepoFile=${fullPath#${REPO_DIR}/};
    if [ "${isRepoFile}" = "${fullPath}" ]; then
        errMsg "$(valMsg ${fullPath}) NOT in the repo
        $(keyMsg ${REPO_DIR})";
    fi
    CHANGELOG=${isRepoFile}; # Relative path of repo
fi

if [ ! -f "${CHANGELOG}" ]; then
    pathName=$(dirname ${CHANGELOG});
    [ ! -e "${pathName}" ] && mkdir -p ${pathName};
    touch "${CHANGELOG}";
fi

# make working repo stash to clean up without lost any data
git stash &>/dev/null || true;
SEMVER_TAG=$(standard-release -x -f SKIP -c ${CHANGELOG} 2>/dev/null | head -n 1 \
    | awk -F':' 'gsub(/[ ]/,"",$2) { print $2; }');
[ -n "${SEMVER_TAG}" ] \
    || errMsg "Get auto semver failed, try install npm $(keyMsg standard-release)";
# make working repo back to previous status
git checkout .
git stash pop &>/dev/null || true;

# Split auto semver into two parts
SEMVER_VAL=$(echo "${SEMVER_TAG}" \
    | awk 'sub(/v/,"",$1) sub(/-/,";",$1) { print $1; }');

AUTO_MMP=$(echo "${SEMVER_VAL}" | awk -F ';' '{ print $1; }');
AUTO_PREREL=$(echo "${SEMVER_VAL}" | awk -F ';' '{ print $2; }');
#debugMsg "$(keyMsg Auto major.minor.patch): [$(valMsg ${AUTO_MMP})]";
#debugMsg "$(keyMsg Auto pre-release-tweak): [$(valMsg ${AUTO_PREREL})]";

AUTO_MAJOR=$(echo "${AUTO_MMP}" | awk -F '.' '{ print $1; }');
AUTO_MINOR=$(echo "${AUTO_MMP}" | awk -F '.' '{ print $2; }');
AUTO_PATCH=$(echo "${AUTO_MMP}" | awk -F '.' '{ print $3; }');

AUTO_TWEAK_TXT="";
AUTO_TWEAK_NUM="";
if [ -n "${AUTO_PREREL}" ]; then
    # auto semver do not return the build-metadata part
    AUTO_TWEAK_TXT=$(echo "${AUTO_PREREL}" | ${_sed} "s/^${SRLC_REG}$/\1/");
    AUTO_TWEAK_NUM=$(echo "${AUTO_PREREL}" | ${_sed} "s/^${SRLC_REG}$/\3/");

    AUTO_TWEAK_TXT=$(echo "${AUTO_TWEAK_TXT}" | ${_sed} -n "/^[a-z]*$/p");
    AUTO_TWEAK_NUM=$(echo "${AUTO_TWEAK_NUM}" | ${_sed} -n "/^[0-9]*$/p");

    if [ -z "${AUTO_TWEAK_TXT}" -a -z "${AUTO_TWEAK_NUM}" ]; then
        errMsg "Auto semver $(keyMsg TWEAK) shoule be one of:\n
    ${SRLC_HELP}";
    fi

    #debugMsg "$(keyMsg Tweak auto text): [$(valMsg ${AUTO_TWEAK_TXT})]";
    #debugMsg "$(keyMsg Tweak auto nums): [$(valMsg ${AUTO_TWEAK_NUM})]";
fi

_major_="$(valMsg ${AUTO_MAJOR})";
[ "${PREV_MAJOR}" != "${AUTO_MAJOR}" ] \
    && _major_="$(msgRed ${AUTO_MAJOR})";

_minor_="$(valMsg ${AUTO_MINOR})";
[ "${PREV_MINOR}" != "${AUTO_MINOR}" ] \
    && _minor_="$(msgRed ${AUTO_MINOR})";

_patch_="$(valMsg ${AUTO_PATCH})";
[ "${PREV_PATCH}" != "${AUTO_PATCH}" ] \
    && _patch_="$(msgRed ${AUTO_PATCH})";

is_sha_tweak_only=true;
_tweak_="$(valMsg ${AUTO_PREREL})";
if [ "${PREV_TWEAK}" != "${AUTO_PREREL}" ]; then
    _tweak_="";
    AUTO_PREREL=""; # clean it
    SEPC=""
    if [ -n "${AUTO_TWEAK_TXT}" ]; then
        is_sha_tweak_only=false;
        AUTO_PREREL="${AUTO_TWEAK_TXT}"
        if [ "${PREV_TWEAK_TXT}" != "${AUTO_TWEAK_TXT}" ]; then
            _tweak_="$(msgRed ${AUTO_TWEAK_TXT})";
        else
            _tweak_="$(valMsg ${AUTO_TWEAK_TXT})";
        fi
        SEPC="."
    fi

    if [ "${#AUTO_TWEAK_NUM}" = "8" -o "${#PREV_TWEAK_NUM}" = "8" ]; then
        is_sha_tweak_only=false;
        # the numberic is YYYYMMDD format, update it
        CURRENT_DATE=$(date +%Y%m%d)
        AUTO_PREREL="${AUTO_PREREL}${SEPC}${CURRENT_DATE}"
        if [ "${CURRENT_DATE}" = "${PREV_TWEAK_NUM}" ]; then
            _tweak_="${_tweak_}${SEPC}$(valMsg ${CURRENT_DATE})";
        else
            _tweak_="${_tweak_}${SEPC}$(msgRed ${CURRENT_DATE})";
        fi
    else
        if [ -n "${#AUTO_TWEAK_NUM}" ]; then
            is_sha_tweak_only=false;
            # update the numberic to the auto increatment
            AUTO_PREREL="${AUTO_PREREL}${SEPC}${AUTO_TWEAK_NUM}"
            _tweak_="${_tweak_}${SEPC}$(msgRed ${AUTO_TWEAK_NUM})";
        fi
    fi

    # always append current SHA1 for release tracing
    full_commit=$(git log --pretty=oneline -1 | cut -f1 -d' ')
    short_commit=${full_commit:0:10}
    if [ "${short_commit}" != "${PREV_TWEAK_SHA}" ]; then
        # update to newest commit SHA1
        _tweak_="${_tweak_}+$(msgRed ${short_commit})";
        AUTO_PREREL="${AUTO_PREREL}+${short_commit}"
    else
        # SHA1 no changed, just keep the old value
        _tweak_="${_tweak_}+$(valMsg ${PREV_TWEAK_SHA})";
        AUTO_PREREL="${AUTO_PREREL}+${PREV_TWEAK_SHA}"
    fi
fi

a_major="${_major_}"
a_minor="${_minor_}"
a_patch="${_patch_}"
a_tweak="${_tweak_}"

BUMP_SEMVER=false;
BUMP_SEMVER_BY_USER=true;
infoMsg "----------------------------------------------------------------";
# The previous latest tag
if ${isGitRepo}; then
    LATEST_TAG=$(git describe --abbrev=0 --tags 2>/dev/null || echo "");
    [ -z "${LATEST_TAG}" ] && LATEST_TAG="init commit, no tags";
    [ -n "${LATEST_TAG}" ] && LATEST_TAG=$(standard-release --newest-tag=true)
fi
infoMsg "The Latest Release Tag: $(msgRed ${LATEST_TAG})";
infoMsg "SemVer FILE => M(${s_major})\tm(${s_minor})\tP(${s_patch})\tT(${s_tweak})";
infoMsg "SemVer AUTO => M(${a_major})\tm(${a_minor})\tP(${a_patch})\tT(${a_tweak})";
infoMsgL "Use AUTO Semantic Version (y/n) [y]: ";
usrInput="Y"; # default value for none interactive mode
${IS_TESTING} && usrInput="Y"; # testing & none interactive mode
${IS_INTERACTIVE} && read -p "" usrInput;
! ${IS_INTERACTIVE} && ! ${__SKIP_ALL_MSG} echo "";
[ -z "${usrInput}" ] && usrInput='Y'; # Just Enter is Yes
if isYes "${usrInput}"; then
    BUMP_SEMVER=true;
    BUMP_SEMVER_BY_USER=false;
    VERSION_MAJOR=${AUTO_MAJOR};
    VERSION_MINOR=${AUTO_MINOR};
    VERSION_PATCH=${AUTO_PATCH};
    VERSION_TWEAK=${AUTO_PREREL};
fi

if ${BUMP_SEMVER_BY_USER}; then
    # The final major
    infoMsgL "New SemVer Major [$(valMsg ${VERSION_MAJOR})]: ";
    usrInput=""; # default value for none interactive mode
    ${IS_INTERACTIVE} && read -p "" usrInput;
    ! ${IS_INTERACTIVE} && ! ${__SKIP_ALL_MSG} echo "";
    case "${usrInput}" in
    "")
        # Just Enter is empty, just use it, no touching
        ;;
    *)
        IS_NUM=$(echo "${usrInput}" | ${_sed} -n "/^[0-9]+$/p");
        [ -z "${IS_NUM}" ] && errMsg "$(keyMsg Major) must be numbers of 0-9.";
        VERSION_MAJOR="${usrInput}";
        BUMP_SEMVER=true;
        ;;
    esac

    # The final minor
    infoMsgL "New SemVer Minor [$(valMsg ${VERSION_MINOR})]: ";
    usrInput=""; # default value for none interactive mode
    ${IS_INTERACTIVE} && read -p "" usrInput;
    ! ${IS_INTERACTIVE} && ! ${__SKIP_ALL_MSG} echo "";
    case "${usrInput}" in
    "")
        # Just Enter is empty, just use it, no touching
        ;;
    *)
        IS_NUM=$(echo "${usrInput}" | ${_sed} -n "/^[0-9]+$/p");
        [ -z "${IS_NUM}" ] && errMsg "$(keyMsg Minor) must be numbers of 0-9.";
        VERSION_MINOR="${usrInput}";
        BUMP_SEMVER=true;
        ;;
    esac

    # The final patch
    infoMsgL "New SemVer Patch [$(valMsg ${VERSION_PATCH})]: ";
    usrInput=""; # default value for none interactive mode
    ${IS_INTERACTIVE} && read -p "" usrInput;
    ! ${IS_INTERACTIVE} && ! ${__SKIP_ALL_MSG} echo "";
    case "${usrInput}" in
    "")
        # Just Enter is empty, just use it, no touching
        ;;
    *)
        IS_NUM=$(echo "${usrInput}" | ${_sed} -n "/^[0-9]+$/p");
        [ -z "${IS_NUM}" ] && errMsg "$(keyMsg Patch) must be numbers of 0-9.";
        VERSION_PATCH="${usrInput}";
        BUMP_SEMVER=true;
        ;;
    esac

    # The final tweak
    is_sha_tweak_only=false; # do not input SHA1 by hand most of time
    infoMsgL "New SemVer Tweak ($(keyMsg SKIP)) [$(valMsg ${VERSION_TWEAK})]: ";
    usrInput=""; # default value for none interactive mode
    ${IS_INTERACTIVE} && read -p "" usrInput;
    ! ${IS_INTERACTIVE} && ! ${__SKIP_ALL_MSG} echo "";
    case "${usrInput}" in
    "")
        # Just Enter is empty, just use it, no touching
        ;;
    "SKIP")
        # Tweak skip, empty the value
        if [ -n "${VERSION_TWEAK}" ]; then
            # Not auto bump, clean ${VS_VFILE} tweak part only
            VERSION_TWEAK="";
            BUMP_SEMVER=true;
        fi
        ;;
    *)
        VERSION_TWEAK="${usrInput}";
        BUMP_SEMVER=true; # new tweak value
        ;;
    esac
fi

VERSION_TWEAK_TXT="";
VERSION_TWEAK_NUM="";
VERSION_TWEAK_SHA="";
# Checking tweak if not empty
[ -n "${VERSION_TWEAK}" ] && {
    USED_TWEAK_TXT=$(echo "${VERSION_TWEAK}" | ${_sed} "s/^${SRLC_REG}$/\1/");
    USED_TWEAK_NUM=$(echo "${VERSION_TWEAK}" | ${_sed} "s/^${SRLC_REG}$/\3/");
    USED_TWEAK_SHA=$(echo "${VERSION_TWEAK}" | ${_sed} "s/^${SRLC_REG}$/\5/");

    USED_TWEAK_TXT=$(echo "${USED_TWEAK_TXT}" | ${_sed} -n "/^[a-z]*$/p");
    USED_TWEAK_NUM=$(echo "${USED_TWEAK_NUM}" | ${_sed} -n "/^[0-9]*$/p");
    USED_TWEAK_SHA=$(echo "${USED_TWEAK_SHA}" | ${_sed} -n "/^[a-f0-9]*$/p");

    if [ -n "${USED_TWEAK_TXT}" ]; then
        IS_OK=false;
        tweakInfo="$(valMsg ${VERSION_TWEAK})";
        for item in ${SRLC_CAN}; do
            [ "${USED_TWEAK_TXT}" = "${item}" ] && IS_OK=true && break;
        done

        if ! ${IS_OK}; then
            errMsg "$(keyMsg TWEAK)(${tweakInfo}) shoule be one of: ${SRLC_HELP}";
        fi
    fi

    VERSION_TWEAK_TXT="${USED_TWEAK_TXT}";
    VERSION_TWEAK_NUM="${USED_TWEAK_NUM}";
    VERSION_TWEAK_SHA="${USED_TWEAK_SHA}";
    #debugMsg "$(keyMsg Final tweak text): [$(valMsg ${VERSION_TWEAK_TXT})]";
    #debugMsg "$(keyMsg Final tweak nums): [$(valMsg ${VERSION_TWEAK_NUM})]";
    #debugMsg "$(keyMsg Final tweak nums): [$(valMsg ${VERSION_TWEAK_SHA})]";
}

if [ -z "${VERSION_TWEAK}" ]; then
    RELEASE_TAG="v${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}"
else
    if ${is_sha_tweak_only}; then
        RELEASE_TAG="v${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}${VERSION_TWEAK}"
    else
        RELEASE_TAG="v${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}-${VERSION_TWEAK}"
    fi
fi

{ [ -z "${VERSION_MAJOR}" ] || [ -z "{$VERSION_MINOR}" ] || [ -z "${VERSION_PATCH}" ]; } \
    && errMsg "Release semver($(valMsg ${RELEASE_TAG})) error";

# Check if RELEASE_TAG is valid semver
if ! $(standard-release -x --is-semver "${RELEASE_TAG}"); then
    errMsg "Invalid release semver($(valMsg ${RELEASE_TAG}))";
fi

if ${isGitRepo}; then
    for tag in $(git tag --list); do
        [ "${tag}" = "${RELEASE_TAG}" ] \
            && errMsg "The semver tag $(valMsg ${tag}) already exists";
    done
fi

_major_="$(valMsg ${VERSION_MAJOR})";
[ "${PREV_MAJOR}" != "${VERSION_MAJOR}" ] \
    && _major_="$(msgRed ${VERSION_MAJOR})";

_minor_="$(valMsg ${VERSION_MINOR})";
[ "${PREV_MINOR}" != "${VERSION_MINOR}" ] \
    && _minor_="$(msgRed ${VERSION_MINOR})";

_patch_="$(valMsg ${VERSION_PATCH})";
[ "${PREV_PATCH}" != "${VERSION_PATCH}" ] \
    && _patch_="$(msgRed ${VERSION_PATCH})";

_tweak_="$(valMsg ${VERSION_TWEAK})";
if [ -n "${VERSION_TWEAK}" ]; then
    _tweak_=""; # clean it
    SEPC=""
    if [ -n "${VERSION_TWEAK_TXT}" ]; then
        if [ "${PREV_TWEAK_TXT}" != "${VERSION_TWEAK_TXT}" ]; then
            _tweak_="$(msgRed ${VERSION_TWEAK_TXT})";
        else
            _tweak_="$(valMsg ${VERSION_TWEAK_TXT})";
        fi
        SEPC="."
    fi

    if [ -n "${VERSION_TWEAK_NUM}" ]; then
        if [ "${PREV_TWEAK_NUM}" != "${VERSION_TWEAK_NUM}" ]; then
            _tweak_="${_tweak_}${SEPC}$(msgRed ${VERSION_TWEAK_NUM})";
        else
            _tweak_="${_tweak_}${SEPC}$(valMsg ${VERSION_TWEAK_NUM})";
        fi
    fi

    if [ -n "${VERSION_TWEAK_SHA}" ]; then
        if [ "${PREV_TWEAK_SHA}" != "${VERSION_TWEAK_SHA}" ]; then
            _tweak_="${_tweak_}+$(msgRed ${VERSION_TWEAK_SHA})";
        else
            _tweak_="${_tweak_}+$(valMsg ${VERSION_TWEAK_SHA})";
        fi
    fi
fi

# Make the output pretty look
maxStrLen=$(maxNum ${#PREV_MAJOR} ${#PREV_MINOR} ${#PREV_PATCH} ${#PREV_TWEAK_NC});

indentA="";
strLen=${#PREV_MAJOR};
while [ ${strLen} -le ${maxStrLen} ]; do
  let strLen++;
  indentA="${indentA} ";
done

indentB="";
strLen=${#PREV_MINOR};
while [ ${strLen} -le ${maxStrLen} ]; do
  let strLen++;
  indentB="${indentB} ";
done

indentC="";
strLen=${#PREV_PATCH};
while [ ${strLen} -le ${maxStrLen} ]; do
  let strLen++;
  indentC="${indentC} ";
done

indentD="";
strLen=${#PREV_TWEAK_NC};
while [ ${strLen} -le ${maxStrLen} ]; do
  let strLen=strLen+1;
  indentD="${indentD} ";
done

#debugMsg "$(keyMsg Max length): [$(valMsg ${maxStrLen})]";
#debugMsg "$(keyMsg Major indent): [${indentA}]";
#debugMsg "$(keyMsg Minor indent): [${indentB}]";
#debugMsg "$(keyMsg Patch indent): [${indentC}]";
#debugMsg "$(keyMsg Tweak indent): [${indentD}]";

infoMsg "----------------------------------------------------------------";
infoMsg "Release Major: $(valMsg ${PREV_MAJOR})${indentA}=> ${_major_}";
infoMsg "Release Minor: $(valMsg ${PREV_MINOR})${indentB}=> ${_minor_}";
infoMsg "Release Patch: $(valMsg ${PREV_PATCH})${indentC}=> ${_patch_}";
infoMsg "Release Tweak: $(valMsg ${PREV_TWEAK})${indentD}=> ${_tweak_}";
infoMsg "Release TagIs: $(msgBlue ${RELEASE_TAG})";

# Update Version
if ${BUMP_SEMVER}; then
    ${_sed} -i.bk "s/${REGEXP_MAJOR}/\1${VERSION_MAJOR}\3/" ${VS_VFILE};
    ${_sed} -i.bk "s/${REGEXP_MINOR}/\1${VERSION_MINOR}\3/" ${VS_VFILE};
    ${_sed} -i.bk "s/${REGEXP_PATCH}/\1${VERSION_PATCH}\3/" ${VS_VFILE};
    ${_sed} -i.bk "s/${REGEXP_TWEAK}/\1${VERSION_TWEAK}\3/" ${VS_VFILE};
    ${_sed} -i.bk "s/${REGEXP_SEMVER}/\1${RELEASE_TAG}\3/" ${VS_VFILE};
    rm ${VS_VFILE}.bk;
fi

infoMsg "----------------------------------------------------------------";
SRA_R=""; # standard-release arguments for changelog release
infoMsgL "Changelog $(keyMsg Release) or $(keyMsg Unreleased) (y/n) [n]: ";
usrInput="N"; # default value for none interactive mode
${IS_TESTING} && usrInput="N"; # testing & none interactive mode
${IS_INTERACTIVE} && read -p "" usrInput;
! ${IS_INTERACTIVE} && ! ${__SKIP_ALL_MSG} echo "";
if isYes "${usrInput}"; then
    SRA_R="-r";
fi

if $CHANGELOG_UPDATE; then
    standard-release -x ${SRA_R} -c ${CHANGELOG} &>/dev/null;
    # Sync CHANGELOG.md release tag to the one really used
    ${_sed} -i.bk "s/${SEMVER_TAG}/${RELEASE_TAG}/g" ${CHANGELOG}
    rm ${CHANGELOG}.bk;
fi

infoMsg "----------------------------------------------------------------";
repo_fname=${CHANGELOG#*${REPO_DIR}/}
infoMsgL "Show $(valMsg ${repo_fname}) Diff (y/n) [n]: ";
usrInput="N"; # default value for none interactive mode
${IS_TESTING} && usrInput="N"; # testing & none interactive mode
${IS_INTERACTIVE} && read -p "" usrInput;
! ${IS_INTERACTIVE} && ! ${__SKIP_ALL_MSG} echo "";
if isYes "${usrInput}"; then
    ${isGitRepo} && git diff ${CHANGELOG};
fi

infoMsg "----------------------------------------------------------------";
repo_fname=${VS_VFILE#*${REPO_DIR}/}
infoMsgL "Show $(valMsg ${repo_fname}) Diff (y/n) [n]: ";
usrInput="N"; # default value for none interactive mode
${IS_TESTING} && usrInput="N"; # testing & none interactive mode
${IS_INTERACTIVE} && read -p "" usrInput;
! ${IS_INTERACTIVE} && ! ${__SKIP_ALL_MSG} echo "";
if isYes "${usrInput}"; then
    ${isGitRepo} && git diff ${VS_VFILE};
fi

infoMsg "----------------------------------------------------------------";
infoMsgL "Project Build Command ($(keyMsg SKIP)) [make]: ";
usrInput="make"; # default value for none interactive mode
${IS_TESTING} && usrInput="SKIP"; # testing & none interactive mode
${IS_INTERACTIVE} && read -p "" usrInput;
! ${IS_INTERACTIVE} && ! ${__SKIP_ALL_MSG} echo "";
[ -z "${usrInput}" ] && usrInput='make'; # Just Enter
if [ "${usrInput}" != "SKIP" ]; then
    ${usrInput}; # the project build command
fi

infoMsg "----------------------------------------------------------------";
infoMsgL "The Commands to Run for Confirming (Commands) []: ";
usrInput=""; # default value for none interactive mode
${IS_TESTING} && usrInput=""; # testing & none interactive mode
${IS_INTERACTIVE} && read -p "" usrInput;
! ${IS_INTERACTIVE} && ! ${__SKIP_ALL_MSG} echo "";
if [ -n "${usrInput}" ]; then
    ${usrInput}; # the executable programme to run
fi

# Commit & Tag
TAG_HDR="chore(auto1): tag ${RELEASE_TAG}";
CMT_HDR="chore(auto2): release ${RELEASE_TAG}";
MSG_BDY="

- Detail changes see ${CHANGELOG}
- Building changelog since ${LATEST_TAG}";

TAG_MSG="${TAG_HDR}${MSG_BDY}";
COMMIT_MSG="${CMT_HDR}${MSG_BDY}";

infoMsg "----------------------------------------------------------------";
infoMsg "The Signed-off Commit Message:";
! ${IS_TESTING} && printf "$(msgGreen "${COMMIT_MSG}")\n";

infoMsg "----------------------------------------------------------------";
infoMsg "The Signed Annotated Tag Message:";
! ${IS_TESTING} && printf "$(msgGreen "${TAG_MSG}")\n";

# Really want to do this
infoMsg "----------------------------------------------------------------";
infoMsgL "Confirm $(valMsg ${VCS}) Commit & Tag (y/n) [n]: ";
usrInput="N"; # default value for none interactive mode
${IS_TESTING} && usrInput="Y"; # testing & none interactive mode
${IS_INTERACTIVE} && read -p "" usrInput;
! ${IS_INTERACTIVE} && ! ${__SKIP_ALL_MSG} echo "";
if isNo "${usrInput}"; then
    errMsg "Release STOP, Confirm with $(keyMsg y) or $(keyMsg Y)";
fi

if isYes "${usrInput}"; then
    if ${isGitRepo}; then
        git add ${VS_VFILE};  # Update version
        git add ${CHANGELOG}; # Update changelog

        if ${IS_TESTING}; then
            git commit -m "${COMMIT_MSG}" &>/dev/null;
            git tag -a "${RELEASE_TAG}" -m "${TAG_MSG}" &>/dev/null;
        else
            git commit --signoff -m "${COMMIT_MSG}";
            git tag --sign -a "${RELEASE_TAG}" -m "${TAG_MSG}";
        fi
    fi
fi

infoMsg "#################";
infoMsg "# Release Done! #";
infoMsg "#################";
