#!/usr/bin/env bash

# Exit the script if any statement returns a non-true return value
set -e
# Show error if used undefined variable
set -u
# Pipe fail if any one of the pipe command failed
set -o pipefail

function supportedVCS
{
    case "$1" in
    "GIT" | "Git" | "git")
        echo "GIT"
        ;;
    "SVN" | "Svn" | "svn")
        echo "SVN"
        ;;
    *)
        echo "UNKNOWN"
        ;;
    esac
}

function guessVCS
{
    if [ -d ${PWD}/.git ]; then
        echo "GIT"; return 0;
    fi

    if [ -d ${PWD}/.svn ]; then
        echo "SVN"; return 0;
    fi

    echo "UNKNOWN"; return 0;
}

case "$#" in
    "0")
        VCS="$(guessVCS)"
        ;;
    "1")
        VCS="$(supportedVCS $1)"
        ;;
    *)
        VCS=""
        ;;
esac

if [ "${VCS}" != "GIT" -a "${VCS}" != "SVN" ]; then
    echo "Usage: ${0##*/} [svn|Svn|SVN|git|Git|GIT]"
    exit 1;
fi

[ "${VCS}" = "SVN" -a ! -d ${PWD}/.svn ] \
    && echo "ERROR: repo is not SVN" && exit 1;
[ "${VCS}" = "GIT" -a ! -d ${PWD}/.git ] \
    && echo "ERROR: repo is not GIT" && exit 1;

_sed=$([ "$(uname)" = "Darwin" ] && echo "sed -E" || echo "sed -r");

[ "${VCS}" = "SVN" ] && {
    REPO_URL=$(svn info | grep "Repository Root:" | awk '{ print $3; }')
    REPO_DIR=$(svn info | grep "Working Copy Root Path:" | awk '{ print $5; }')
    REPO_SUB_DIR=$(svn info | grep "Relative URL:" \
        | awk 'sub(/\^\//,"",$3) sub(/\^\\/,"",$3) { print $3; }')
    [ -z "${REPO_SUB_DIR}" ] && REPO_SUB_DIR="$PWD"

    REPO_HASH=$(svn info | grep "Revision:" | awk '{ print $2; }')
    SVN_SUB_HASH=$(svn info | grep "Last Changed Rev:" | awk '{ print $4; }')
    REPO_HASH="${REPO_HASH}.${SVN_SUB_HASH}"

    REPO_MODIFY_TIME=$(svn info | grep "Last Changed Date:" \
        | awk '{ print $4, $5, $6; }')
}

[ "${VCS}" = "GIT" ] && {
    REPO_URL=$(git remote -v | grep "origin" | awk '{ print $2; }' | head -n 1)
    REPO_SUB_DIR="$PWD"
    REPO_DIR=$(git rev-parse --show-toplevel)
    REPO_SUB_DIR="${REPO_SUB_DIR##${REPO_DIR}}"
    [ -z "${REPO_SUB_DIR}" ] && REPO_SUB_DIR="${REPO_DIR}"

    REPO_HASH=$(git log --oneline -1 | awk '{ print $1; }')
    REPO_MODIFY_TIME=$(git log -1 --date=iso8601 | grep "Date:" \
        | awk '{ print $2, $3, $4; }')
}

######################################################################
# Version file to auto sync SVN repo info
VS_VFILE="${REPO_DIR}/scripts/version"

# Import normal shell function-util
# - IS_DEBUG_MODE=true;
# - IS_VERBOSE_MODE=true;
source ${REPO_DIR}/scripts/utils.sh;
IS_DEBUG_MODE=false;

if true; then # Example 1
# Remote repo URL, for example
# - "svn://localhost/abc"
# - "http://localhost/abc.git"
VS_REPO_URL="#define MY_REPO_URL"
# Must be consist of [0-9a-z.]
VS_REPO_HASH="#define MY_REPO_HASH"
# iso8601: "2019-01-19 01:00:52 +0800"
VS_MODIFY_TIME="#define MY_MODIFY_TIME"
fi

if true; then # Example 2
VS_REPO_URL="const char *MY_REPO_URL ="
VS_REPO_HASH="const char *MY_REPO_HASH ="
VS_MODIFY_TIME="const char * MY_MODIFY_TIME ="
fi

if true; then # Example 3
VS_REPO_URL="const String MY_REPO_URL ="
VS_REPO_HASH="const String MY_REPO_HASH ="
VS_MODIFY_TIME="const String MY_MODIFY_TIME ="
fi
######################################################################

if [ ! -f ${VS_VFILE} ]; then
    errMsg "Do not exits $(keyMsg ${VS_VFILE})";
fi

# The version file should be one file of the repo subdirectory
fullPath=$(realpath ${VS_VFILE});
isRepoFile=${fullPath#${REPO_DIR}/};
if [ "${isRepoFile}" = "${fullPath}" ]; then
    errMsg "$(keyMsg ${VCS}): $(valMsg ${fullPath}) NOT in the repo
       $(keyMsg ${REPO_DIR})";
fi
VS_VFILE=${isRepoFile}; # Relative path of repo

infoMsg "$(keyMsg ${VCS}): Local Repo: $(valMsg ${REPO_DIR})";
infoMsg "$(keyMsg ${VCS}): Remote Repo: $(valMsg ${REPO_URL})";
infoMsg "$(keyMsg ${VCS}): Working Path: $(valMsg ${REPO_SUB_DIR})";
infoMsg "-------------------------------------------------";
infoMsg "$(keyMsg ${VCS}): Repo Hash: $(valMsg ${REPO_HASH})";
infoMsg "$(keyMsg ${VCS}): Timestamp: $(valMsg ${REPO_MODIFY_TIME})";
infoMsg "-------------------------------------------------";

# Escape meta-char for RegExp
#   (   =>  \(
# space =>  \s+
_VS_REPO_URL_=$(echo "${VS_REPO_URL}" \
    | awk -F';' 'sub(/\(/,"\(",$1) gsub(/ /,"\s+",$1) gsub(/\*/,"\*",$1) { print $1; }');
_VS_MODIFY_TIME_=$(echo "${VS_MODIFY_TIME}" \
    | awk -F';' 'sub(/\(/,"\(",$1) gsub(/ /,"\s+",$1) gsub(/\*/,"\*",$1) { print $1; }');
_VS_REPO_HASH_=$(echo "${VS_REPO_HASH}" \
    | awk -F';' 'sub(/\(/,"\(",$1) gsub(/ /,"\s+",$1) gsub(/\*/,"\*",$1) { print $1; }');

# RegExp Pattern: URL
URL_A="((http:\/\/)|(https:\/\/)|(svn:\/\/)|(git@))"
URL_B="[0-9A-Za-z_@:\\\\\/\.-]+"
REGEXP_REPO_URL="^(${_VS_REPO_URL_}\s+\\\")(${URL_A}${URL_B})(\\\"\s*.*)$";

# RegExp Pattern: Hash
REGEXP_REPO_HASH="^(${_VS_REPO_HASH_}\s+\\\"*)([0-9a-z\.]+)(\\\"*\s*.*)$";

# RegExp Pattern: ISO-8601: 2019-01-19 01:00:52 +0800
REGEXP_TMZ="[0-9]{4}"
REGEXP_YMD="[0-9]{4}-[0-9]{2}-[0-9]{2}"
REGEXP_HMS="[0-9]{2}:[0-9]{2}:[0-9]{2}"
REGEXP_DTZ="${REGEXP_YMD}\s+${REGEXP_HMS}\s+\+${REGEXP_TMZ}"
REGEXP_MODIFY_TIME="^(${_VS_MODIFY_TIME_}\s+\\\"*)(${REGEXP_DTZ})(\\\"*\s*.*)$";

_REPO_URL_=$(echo "${REPO_URL}" \
    | awk 'gsub(/\\/,"\\\\\\",$1) gsub(/\//,"\/",$1) gsub(/\./,"\.",$1) \
           gsub(/\-/,"\-",$1) gsub(/\:/,"\:",$1) { print $1; }');

${_sed} -i.bk "s/${REGEXP_REPO_URL}/\1${_REPO_URL_}\8/" ${VS_VFILE};
${_sed} -i.bk "s/${REGEXP_REPO_HASH}/\1${REPO_HASH}\3/" ${VS_VFILE};
${_sed} -i.bk "s/${REGEXP_MODIFY_TIME}/\1${REPO_MODIFY_TIME}\3/" ${VS_VFILE};

rm -rf ${VS_VFILE}.bk
