#ifndef BUILD_CONFIG_VERSION_H
#define BUILD_CONFIG_VERSION_H

#define XXX_VERSION_MAJOR 1
#define XXX_VERSION_MINOR 2
#define XXX_VERSION_PATCH 3
#define XXX_VERSION_TWEAK "pre+20181221"

#endif // BUILD_CONFIG_VERSION_H
